"""Initial migration

Revision ID: c953e04462fe
Revises: 
Create Date: 2025-01-08 21:43:09.151509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c953e04462fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='sizes'), nullable=True),
    sa.Column('color', sa.Enum('RED', 'BLUE', 'BLACK', 'WHITE', 'PINK', 'PURPLE', 'GREEN', name='colors'), nullable=True),
    sa.Column('design', sa.Enum('STRAW_HAT_JOLLY_ROGER', 'RORONOA_ZORO_SWORDS', 'GOING_MERRY', 'THOUSAND_SUNNY', 'MONKEY_D_LUFFY', 'PIRATE_KING', 'WANTED_POSTER', name='printdesigns'), nullable=True),
    sa.Column('material', sa.Enum('COTTON', 'POLYSTER', 'MIXED', name='materials'), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SHIPPED', 'DELIVERED', 'CANCELED', 'RETURNED', name='orderstatus'), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('resources')
    # ### end Alembic commands ###
